# Generated by Django 5.1.2 on 2024-11-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='icon',
            field=models.ImageField(blank=True, upload_to='task_icon'),
        ),
    ]
