# Generated by Django 5.1.2 on 2024-11-28 17:40

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_task_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='task_icon/'),
        ),
    ]
